repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.0
  hooks:
    - id: ruff
      types_or: [python, pyi]
      args: [--fix, --line-length=100]
      # Only lint src/ and tests/
      files: |
        (?x)^(
          src/|
          tests/
        )
      # and ignore ipynb-generated Python files if needed:
      exclude: |
        (?x)^(
          examples/.*|
          .*nbconvert.*|
          .*nbconverted.*|
          .*\.ipynb$
        )
